from datetime import datetime


# ==========================================================
# Helper Functions
# ==========================================================

def safe_value(value, default="Unknown"):
    """
    Return a readable value when data is missing.
    """

    if value is None or value == "":
        return default

    return value


def get_risk_priority(verdict):
    """
    Convert risk verdict into SOC priority.
    """

    if verdict == "HIGH RISK":
        return "HIGH"

    if verdict == "MEDIUM RISK":
        return "MEDIUM"

    return "LOW"


# ==========================================================
# Generate Investigation Report
# ==========================================================

def generate_report(email_info, risk_result):
    """
    Generate a structured SOC-style phishing investigation report.

    Parameters:
        email_info:
            Parsed and analyzed email information.

        risk_result:
            Output generated by risk_engine.calculate_risk()

    Returns:
        Dictionary containing the final investigation report.
    """

    # ------------------------------------------------------
    # Basic Information
    # ------------------------------------------------------

    subject = safe_value(
        email_info.get("subject")
    )

    sender = safe_value(
        email_info.get("from")
    )

    reply_to = safe_value(
        email_info.get("reply_to")
    )

    # ------------------------------------------------------
    # Risk Information
    # ------------------------------------------------------

    score = risk_result.get(
        "score",
        0
    )

    verdict = risk_result.get(
        "verdict",
        "UNKNOWN"
    )

    findings = risk_result.get(
        "findings",
        []
    )

    risk_breakdown = risk_result.get(
        "risk_breakdown",
        []
    )

    priority = get_risk_priority(
        verdict
    )

    # ------------------------------------------------------
    # URL Information
    # ------------------------------------------------------

    urls = email_info.get(
        "urls",
        []
    )

    url_analysis = email_info.get(
        "url_analysis",
        []
    )

    # ------------------------------------------------------
    # Attachment Information
    # ------------------------------------------------------

    attachments = email_info.get(
        "attachments",
        []
    )

    # ------------------------------------------------------
    # Authentication Information
    # ------------------------------------------------------

    authentication = email_info.get(
        "authentication_analysis",
        {}
    )

    # ------------------------------------------------------
    # VirusTotal Information
    # ------------------------------------------------------

    vt_results = email_info.get(
        "vt_results",
        []
    )

    # ======================================================
    # Build IOC Section
    # ======================================================

    iocs = {

        "urls": urls,

        "domains": email_info.get(
            "domains",
            []
        ),

        "ip_addresses": email_info.get(
            "ip_addresses",
            []
        ),

        "attachments": [
            {
                "filename": attachment.get(
                    "filename",
                    "Unknown"
                ),

                "sha256": attachment.get(
                    "sha256",
                    "Unknown"
                )
            }

            for attachment in attachments
        ]

    }

    # ======================================================
    # Recommended Actions
    # ======================================================

    recommended_actions = []

    if verdict == "HIGH RISK":

        recommended_actions.extend([
            "Quarantine the email if it is still present in the mailbox.",
            "Do not open or execute any attached files.",
            "Block confirmed malicious URLs/domains after validation.",
            "Check whether the recipient interacted with the email.",
            "Review endpoint and proxy/DNS logs for related activity.",
            "Search for the same sender, domain, or indicators across the environment."
        ])

    elif verdict == "MEDIUM RISK":

        recommended_actions.extend([
            "Review the suspicious indicators manually.",
            "Validate the sender and intended recipient.",
            "Investigate suspicious URLs before allowing user interaction.",
            "Review attachment metadata and reputation.",
            "Search the environment for related indicators."
        ])

    else:

        recommended_actions.extend([
            "No immediate containment action is indicated by the available evidence.",
            "Continue monitoring if other suspicious indicators are reported.",
            "Validate the email context if it was unexpectedly received."
        ])

    # ======================================================
    # Analyst Conclusion
    # ======================================================

    if verdict == "HIGH RISK":

        conclusion = (
            "The email contains multiple indicators associated "
            "with phishing or malicious activity. Further SOC "
            "investigation and containment are recommended."
        )

    elif verdict == "MEDIUM RISK":

        conclusion = (
            "The email contains some suspicious characteristics. "
            "Additional analyst validation is recommended before "
            "considering the email benign."
        )

    else:

        conclusion = (
            "The available indicators do not currently provide "
            "strong evidence of phishing activity."
        )

    # ======================================================
    # Final Report
    # ======================================================

    report = {

        "report_metadata": {

            "generated_at": datetime.utcnow().isoformat()
            + "Z",

            "report_type":
                "Phishing Email Investigation",

            "analysis_engine":
                "SOC Phishing Analyzer"

        },

        "email_summary": {

            "subject": subject,

            "sender": sender,

            "reply_to": reply_to

        },

        "risk_assessment": {

            "score": score,

            "verdict": verdict,

            "priority": priority

        },

        "authentication": {

            "spf": authentication.get(
                "spf",
                "UNKNOWN"
            ),

            "dkim": authentication.get(
                "dkim",
                "UNKNOWN"
            ),

            "dmarc": authentication.get(
                "dmarc",
                "UNKNOWN"
            )

        },

        "ioc_summary": iocs,

        "url_analysis": url_analysis,

        "attachment_analysis": attachments,

        "virustotal_results": vt_results,

        "findings": findings,

        "risk_breakdown": risk_breakdown,

        "recommended_actions": recommended_actions,

        "conclusion": conclusion

    }

    return report